---

 - name: Install fail2ban
   package:
     name: fail2ban
     state: present
   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
   tags: security

 - name: Copy jail configs
   copy:
     src: etc/fail2ban/jail.d/
     dest: /etc/fail2ban/jail.d/
     mode: 644
     owner: root
     group: root
   notify:
    - restart fail2ban service
   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
   tags: security

 - name: Delete default fail2ban config.
   file:
     path: /etc/fail2ban/conf.d/defaults-debian.conf
     state: absent
   notify:
    - restart fail2ban service
    - restart ssh service
   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
   tags: security
