---
 - name: No password requirement for sudo access in deb familiy
   lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"
   tags: security
   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

 - name: No password requirement for sudo access in rhel familiy
   lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%sudo ALL=(ALL) NOPASSWD: ALL'"
   tags: security
   when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
